status: 1
pattern: '[node:field_stop_id:value]-[node:field_stop_name:value]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.bus_stop_page
new_content_behavior: 1
