_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  better_search: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  cacheexclude: 0
  captcha: 0
  ckeditor: 0
  ckeditor5: 0
  colorbox: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  contact: 0
  contact_block: 0
  contextual: 0
  cshs: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  db_custom_tools: 0
  dblog: 0
  draggableviews: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  formblock: 0
  google_analytics: 0
  google_tag: 0
  help: 0
  history: 0
  ict_gtfs: 0
  ict_routes_react_app: 0
  image: 0
  imce: 0
  inline_entity_form: 0
  inline_responsive_images: 0
  it_route_trip_tools: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  layout_discovery: 0
  link: 0
  mailsystem: 0
  media: 0
  media_entity_generic: 0
  media_entity_instagram: 0
  media_entity_twitter: 0
  menu_block: 0
  menu_block_title: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  module_filter: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  profile_switcher: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  responsive_image: 0
  rest: 0
  saml_sp: 0
  saml_sp_drupal_login: 0
  scheduled_updates: 0
  search: 0
  search_api: 0
  search_api_attachments: 0
  search_api_page: 0
  search_api_pantheon: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  sidr: 0
  simplify: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  smtp: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  time_field: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_accordion: 0
  views_bootstrap: 0
  views_conditional: 0
  views_data_export: 0
  views_field_view: 0
  views_infinite_scroll: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_templates: 0
  views_ui: 0
  we_megamenu: 0
  webform: 0
  webform_location_geocomplete: 0
  webform_node: 0
  webform_ui: 0
  webform_views: 0
  workbench_moderation: 0
  menu_link_content: 1
  pathauto: 1
  cshs_menu_link: 5
  menu_link_weight: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  seven: 0
  bootstrap: 0
  transit: 0
  adminimal_theme: 0
profile: standard
